channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python # =3.8.20
  - simpleitk
  - ipykernel
  - matplotlib
  - pandas
  - scikit-learn
  - tensorflow
  - pytorch
  - pip
  - numpy # =1.22.0
  - pip:
      - pyradiomics # =3.1.0